# Generated by Django 3.2.3 on 2021-06-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='subject',
            new_name='full_name',
        ),
    ]
