# Generated by Django 3.2.3 on 2021-06-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagLine', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='landing_img/')),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand_logo/')),
            ],
        ),
    ]
