# Generated by Django 3.2.3 on 2021-06-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_homecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, unique=True)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='brand_logo/')),
            ],
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='brand_logo',
        ),
    ]
