# Generated by Django 3.2.3 on 2021-05-31 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='phone_number',
        ),
    ]
