# Generated by Django 3.2.3 on 2021-06-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_userprofileadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileAdmin',
        ),
    ]
