# Generated by Django 3.2.3 on 2021-06-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210604_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
